services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_PASSWORD: bankpassword
      POSTGRES_USER: bankuser
      POSTGRES_DB: bankdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
      postgres_data: